name: app_admin
description: "Admin Portal for Medical Booking System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.4.9
  hooks_riverpod: ^2.4.9
  flutter_hooks: ^0.20.4

  # Navigation
  go_router: ^13.0.1

  # Network
  dio: ^5.4.0

  # JSON & Serialization
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # Storage
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.2.2

  # UI Utils
  google_fonts: ^6.1.0
  intl: ^0.20.2
  toastification: ^2.0.0
  fl_chart: ^0.69.0
  data_table_2: ^2.5.15
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # Code Generation
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.6

flutter:
  uses-material-design: true
